color0 #f2e9e1
color1 #b4637a
color2 #286983
color3 #ea9d34
color4 #56949f
color5 #907aa9
color6 #d7827e
color7 #575279
color8 #9893a5
color9 #b4637a
color10 #286983
color11 #ea9d34
color12 #56949f
color13 #907aa9
color14 #d7827e
color15 #575279
background #faf4ed
selection_foreground #575279
cursor #b4637a
cursor_text_color #faf4ed
foreground #575279
selection_background #dfdad9
active_border_color #b4637a
inactive_border_color #907aa9

active_tab_foreground   #faf4ed
active_tab_background   #b4637a
inactive_tab_foreground #797593
inactive_tab_background #f2e9e1
cursor_trail_color      #797593
