themes:
  - name: "rose-pine"
    colors:
     - "#191724"
     - "#1f1d2e"
     - "#26233a"
     - "#6e6a86"
     - "#908caa"
     - "#e0def4"
     - "#eb6f92"
     - "#f6c177"
     - "#ebbcba"
     - "#31748f"
     - "#9ccfd8"
     - "#c4a7e7"
     - "#21202e"
     - "#403d52"
     - "#524f67"
  - name: "rose-pine-moon"
    colors:
     - "#232136"
     - "#2a273f"
     - "#393552"
     - "#6e6a86"
     - "#908caa"
     - "#e0def4"
     - "#eb6f92"
     - "#f6c177"
     - "#ea9a97"
     - "#3e8fb0"
     - "#9ccfd8"
     - "#c4a7e7"
     - "#2a283e"
     - "#44415a"
     - "#56526e"
  - name: "rose-pine-dawn"
    colors:
     - "#faf4ed"
     - "#fffaf3"
     - "#f2e9e1"
     - "#9893a5"
     - "#797593"
     - "#575279"
     - "#b4637a"
     - "#ea9d34"
     - "#d7827e"
     - "#286983"
     - "#56949f"
     - "#907aa9"
     - "#f4ede8"
     - "#dfdad9"
     - "#cecacd"
  - name: "rose-pine-all"
    colors:
     - "#191724"
     - "#1f1d2e"
     - "#26233a"
     - "#6e6a86"
     - "#908caa"
     - "#e0def4"
     - "#eb6f92"
     - "#f6c177"
     - "#ebbcba"
     - "#31748f"
     - "#9ccfd8"
     - "#c4a7e7"
     - "#21202e"
     - "#403d52"
     - "#524f67"
     - "#232136"
     - "#2a273f"
     - "#393552"
     - "#6e6a86"
     - "#908caa"
     - "#e0def4"
     - "#eb6f92"
     - "#f6c177"
     - "#ea9a97"
     - "#3e8fb0"
     - "#9ccfd8"
     - "#c4a7e7"
     - "#2a283e"
     - "#44415a"
     - "#56526e"
     - "#faf4ed"
     - "#fffaf3"
     - "#f2e9e1"
     - "#9893a5"
     - "#797593"
     - "#575279"
     - "#b4637a"
     - "#ea9d34"
     - "#d7827e"
     - "#286983"
     - "#56949f"
     - "#907aa9"
     - "#f4ede8"
     - "#dfdad9"
     - "#cecacd"
